Fix/{normalize study phase values}
opentrials/processors pull request #103
Opened 2017-01-17 21:23 UTC by arthurSena

We opted to implement a solution based on a CSV file representing a two-way table(variation and its normalization). This file is accessed in order to match a phase variation
with its normalized forms. 

Since a Trial may be in one or more Phases simutaneously and, as it was suggested,we decided that the return of the method should be an array of phases. 
However, 'knex' does not support said type so we decided to alter the type of the 'study_phase' column to 'jsonb'. 

With this solution, whenever a new variation arrives the CSV file needs to be updated.
Furthermore, a new schema file was generated, updating tests/dbs.

With these modifications, changes were needed on the Api repository. In which the migration and seeds were updated, generating another [PR](https://github.com/opentrials/api/pull/136).

2017-01-20 19:01 UTC, vitorbaptista requested changes
I think this is the way to go, there're just a couple changes and simplifications I'd like to do before merging.

The main simplification is, instead of saving the variations as a CSV and converting it to a dict, save it as a JSON like:

```json
{
    "Phase 1/2": [
         "Phase 1",
         "Phase 2"
    ],
    ...
}
```

This makes the code simpler (you can remove the `build_phase_variation_map()` method) and the variation file becomes more readable. Then, in the `get_normalized_phase()`, you can simply do:

```python
if phase in normalized_phases:
    result = normalized_phases[phase]
else:
    logger.debug('Unable to normalize phase', phase)
    if not phase:
        result = phase
    else:
        result = [phase]
return result
```

As we're only normalizing when we find an exact match, there's no need to log when we're successful.

2017-01-20 19:01 UTC, vitorbaptista commented on tests/processors/base/normalizers/test_phase_normalizer.py
> +    @pytest.mark.parametrize('test_input,expected', [
No need to test every possibility here. Try just a couple cases and the "extremes" (e.g. `None`, a phase we don't have the mapping for, etc.)

2017-01-20 19:01 UTC, vitorbaptista commented on tests/processors/base/normalizers/test_phase_normalizer.py
> +import pytest
The usual importing order we follow is:

1. Standard libraries
2. Third-party libraries
3. Our modules

2017-01-20 19:01 UTC, vitorbaptista commented on processors/base/normalizers/phase_normalizer.py
> +                                      'phases_variations.csv'))
Move the path to a constant, so we can avoid breaking the line here.

2017-01-20 19:01 UTC, vitorbaptista commented on processors/base/normalizers/phase_normalizer.py
> +        logger.debug('Unsuccessfully phase normalization \'None\'')
Remember that `phase` can be any falsy value, like `[]`, `()`, `0`, not only `None`, so it's better to log the `phase` value itself.

2017-01-20 19:05 UTC, vitorbaptista commented
About using `jsonb` instead of `text[]`, have you tried using `table.specificType('study_phase', 'text[]')`? If so, did you have any problems with it?

2017-01-20 19:14 UTC, arthurSena commented
Yes, we did and it works fine. 
Acctually, we have already made the changes and we're going to commit them soon.

2017-01-24 17:51 UTC, vitorbaptista commented on processors/base/normalizers/phases_variations.json
> +    "Phase 2"
Are these repeating values a mistake? There are a few cases of this (e.g. on `Phase 3` and `Phase 1/Phase 2`)

2017-01-24 17:56 UTC, vitorbaptista commented on processors/base/normalizers/phase_normalizer.py
> +            phase_suggestions = phase
Change this to:

```python
if phase:
    phase_suggestions = [phase]
```

And initialize `phase_suggestions = None` before line 26, so if `phase` is falsy (i.e. it's an empty string, `None`, an empty array, etc.) we would return None.

2017-01-24 17:56 UTC, vitorbaptista commented on tests/processors/base/normalizers/test_phase_normalizer.py
> +            ('[]', ['[]']),
Not sure about values like `'()'` and `'[]'` (feel like a typo), but an empty string should return `None` as well. See https://github.com/opentrials/processors/pull/103/files#r97609345 for a suggestion on how to do so.

2017-01-25 17:02 UTC, vitorbaptista approved these changes

2017-01-25 17:59 UTC, merged

2017-01-25 18:00 UTC, vitorbaptista commented
@arthurSena thanks for the PR and congratulations on your first code merged :beers: 

Looking forward for the next ones :smile: