Update contrib docs
opentrials/processors pull request #110
Opened 2017-01-26 19:50 UTC by felipevieira

2017-01-27 10:01 UTC, vitorbaptista requested changes

2017-01-27 10:01 UTC, vitorbaptista commented on CONTRIBUTING.md
> +pip install --upgrade -r requirements.txt
No need for `--upgrade` here

2017-01-27 10:01 UTC, vitorbaptista commented on requirements.txt
> +tox
We expect `tox` to be installed globally, as it isn't a project requirement. You could tell this on the `Run tests` part of the docs, like:

> To run the tests, you need `tox` installed. We recommend you to install it globally with `pip install -g tox`.

2017-01-27 17:58 UTC, felipevieira reviewed
Resolved

2017-01-30 12:52 UTC, vitorbaptista approved these changes

2017-01-30 12:53 UTC, merged