Cochrane processor
opentrials/processors pull request #59
Opened 2016-09-22 15:34 UTC by georgiana-b

Processor for extracting risk of bias results from Cochrane reviews.

2016-09-27 09:27 UTC, georgiana-b commented
Using the fuzzy search of http://www.ncbi.nlm.nih.gov to get PubMed IDs seems a bit of a hassle so  I ran the processor with different ways of matching (risk of bias results to trials) to see it's worth keeping it. Here are the results:

* 73 matches using the fuzzy search of http://www.ncbi.nlm.nih.
* 93 matches using OpenTrials API  fuzzy search - leads to overmatches if we search only by `title` so it can be a viable solution only if we add  `authors` attribute to the publications in `trials` index or make another index for publications
* 53 matches without any fuzzy search

2016-09-29 11:16 UTC, vitorbaptista requested changes

2016-09-29 11:16 UTC, vitorbaptista commented on processors/base/writers/risk_of_bias.py
> +    existing = [r for r in helpers.iter_rows(conn, **query_params)]
From https://github.com/opentrials/api/pull/87, there can't be multiple ROB with the same `source_url` and `study_id`, so you can simplify this query by doing `conn['database']['risk_of_biases'].find_one(study_id=rob['study_id'], source_url=rob['source_url'])`

2016-09-29 11:16 UTC, vitorbaptista commented on processors/base/writers/risk_of_bias.py
> +        object = None
I know this pattern is used in other parts of the code, but don't use Python's reserved words as variables (we'll remove the others). You can do:

``` python
rob = conn['database']['risk_of_biases'].find_one(study_id=rob['study_id'], source_url=rob['source_url'])

if not rob:
    rob = {
        # ...
    }
```

2016-09-29 11:16 UTC, vitorbaptista commented on processors/base/writers/risk_of_bias.py
> +        object['id'] = uuid.uuid4().hex
Never use `uuid4` for ID fields. Use `uuid.uuid1().hex` instead.

2016-09-29 11:16 UTC, vitorbaptista commented on processors/base/writers/risk_of_bias.py
> +        object = None
Same as my comments on `write_rob()`:
- Don't use Python's reserved words as variable names
- Prefer using `rob_criteria = conn['database']['risk_of_biases'].find_one(name=rob_criteria['name'])`

2016-09-29 11:16 UTC, vitorbaptista commented on processors/base/writers/risk_of_bias.py
> +        object['name'] = rob_criteria['name']
Instead of declaring the variable as `{}` and then changing its attributes, use:

``` python
rob_criteria = {
    'id': uuid.uuid1().hex,  # Note we're using UUID1 instead of UUID4
    # ...
}
```

2016-09-29 11:16 UTC, vitorbaptista commented on processors/base/writers/risk_of_bias.py
> +    })
As you're updating only a single attribute, prefer `rob_criteria['updated_at'] = timestamp`.

2016-09-29 11:16 UTC, vitorbaptista commented on processors/base/writers/risk_of_bias.py
> +    """Write risk_of_bias_criteria to database.
As a `risk_of_bias_criteria` only has a `name` attribute, and we use the `name` to find it in the database, updating doesn't make much sense (as we're updating a row without changing any of its values). This method should only write the `risk_of_bias_criteria` if it doesn't exist, or return its `id` if it does.

2016-09-29 11:16 UTC, vitorbaptista commented on processors/base/writers/risk_of_bias.py
> +    """Write risk_of_bias-risk_of_bias_criteria to database.
The `docstrings` are incorrect, as you're always returning `None`. I understand that you did so because it has a composite primary key. Maybe instead of having a `write_rob_rob_criteria()` function, it would be better to write it as part of the `write_rob_criteria()` function.

2016-09-29 11:16 UTC, vitorbaptista commented on processors/cochrane/extractors.py
> +        matches = {id: val for id, val in correlations.items()
`id` is a reserved word in Python. Don't use it as a variable name. I usually use `key` instead.

2016-09-29 11:16 UTC, vitorbaptista commented on processors/cochrane/extractors.py
> +        rob_name = result.get('rob_name', '')
As a small defensive programming technique, you can use `rob_name = result.get('rob_name') or ''` instead, to cover the case where `result['rob_name'] == None`

2016-09-29 11:16 UTC, vitorbaptista commented on processors/cochrane/extractors.py
> +        if len(matched_keys) > 1:
You can simplify this by defining `id = None` before this `if`, as this'll allow you to remove the two `else: id = None`

2016-09-29 11:16 UTC, vitorbaptista commented on processors/cochrane/processor.py
> +# NOTE: Match directly to `database` publications after `pubmed_id` is added
Use `FIXME` instead and fix the indentation

2016-09-29 11:16 UTC, vitorbaptista commented on processors/cochrane/processor.py
> +    return [trial['id']]
`trial` will be None if it can't be found, so you need to test for this case here, just changing the last line (100) to:

``` python
if trial:
    return [trial['id']]
```

2016-09-29 11:16 UTC, vitorbaptista commented on processors/cochrane/processor.py
> +    for id in useful_ids:
Don't use `id` as a variable name. You could use something like `_id`.

2016-09-29 11:16 UTC, vitorbaptista commented on processors/cochrane/processor.py
> +                    break
Log if there're more than 1 matched trial.

2016-09-29 11:16 UTC, vitorbaptista commented on tests/processors/cochrane/test_extractors.py
> +                    {'name':'6', 'value':'no'}]
Instead of using IDs as names, use the actual human-readable names

2016-10-04 16:15 UTC, vitorbaptista commented on processors/base/writers/risk_of_bias.py
> +    ex_rob.update({
Could  check here if `ex_rob.get('trial_id') != rob['trial_id'] or ex_rob.get('source_id') != rob['source_id']`, so only update if needed

2016-10-04 17:09 UTC, vitorbaptista commented on processors/base/writers/risk_of_bias.py
> +                                                      ensure=False)
Here we're only creating the `rob_crt`. Updating it is useless, as we just change the `updated_at` timestamp.

2016-10-04 17:09 UTC, vitorbaptista commented on processors/cochrane/extractors.py
> +        'type': 'other',
I think this should be "Cochrane Schizophrenia". Also add `url: http://schizophrenia.cochrane.org/`

2016-10-04 17:09 UTC, vitorbaptista commented on processors/cochrane/processor.py
> +                if len(unique_trails) == 1:
Typo `trails` -> `trials`

2016-10-04 17:09 UTC, vitorbaptista commented on processors/cochrane/processor.py
> +                                 reference, matching_trials)
Use `unique_trials` instead

2016-10-04 17:09 UTC, vitorbaptista commented on processors/cochrane/processor.py
> +                match = re.search(r'{0}[\s]*[^\d]*(\d+)'.format(_id), value).group(1)
This regexp matches things like `NCT lorem ipsum foo bar 12345678`. Also, extract the regexp to a variable, as you're using the same on line 130.

2016-10-05 07:59 UTC, georgiana-b commented on processors/base/writers/risk_of_bias.py
> +                                                      ensure=False)
Isn't that what `updated_at` is for? :slightly_smiling_face:

2016-10-05 14:03 UTC, georgiana-b commented
@vitorbaptista  Sorry for  the bulk of commits. I pulled with `rebase` from master. The latest changes that haven't been reviewed so far are in the last 3 commits (de27f0e, 58290cb, 04fcc18 ).

2016-10-07 21:10 UTC, vitorbaptista approved these changes

2016-10-07 21:16 UTC, merged